### PR TITLE
Snippets for new batch track

### PR DESCRIPTION
**Pull request by GroophyLifefor**
Hi @ErikSchierboom , Here mine snippet comment configuration. Can you review please 😄

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
You're missing the tests: https://github.com/exercism/snippet-extractor?tab=readme-ov-file#add-golden-tests

**Comment by GroophyLifefor** [comment]
How can I see generated snippet to find problem ?

**Comment by GroophyLifefor** [comment]
my expected was 
```bat
@echo off

SET source_dir=C:\Users\Username\Documents
SET backup_dir=D:\Backup

echo Starting backup...

IF NOT EXIST "%source_dir%" (
    echo Source not found. Exiting...
    exit /b
)

IF NOT EXIST "%backup_dir%" (
    echo Creating backup directory...
    mkdir "%backup_dir%"
)

xcopy "%source_dir%\*" "%backup_dir%\" /E /I /Y

echo Backup complete.
pause
```

but the tool waits
```cmd
@echo off

SET source_dir=C:\\Users\\Username\\Documents
SET backup_dir=D:\\Backup

echo Starting backup...

IF NOT EXIST \"%source_dir%\" (
    echo Source not found. Exiting...
    exit /b
)

IF NOT EXIST \"%backup_dir%\" (
    echo Creating backup directory...    mkdir \"%backup_dir%\"
)

xcopy \"%source_dir%\\*\" \"%backup_dir%\\\" /E /I /Y

echo Backup complete.
pause
```

I'm a little bit confused.

**Comment by ErikSchierboom** [comment]
Did you look at the actual value in the output?

**Comment by GroophyLifefor** [comment]
> Did you look at the actual value in the output?

I do and I see that, in the `exit /b\n    )` part, parsing got stop, but code not ends

**Comment by ErikSchierboom** [comment]
Could you please read the [README])(https://github.com/exercism/snippet-extractor) carefully to understand what exactly the snippet extractor is doing?

**Comment by iHiD** [comment]
Specifically, I think you've missed: "the snippet extractor extracts the first ten "interesting" (non-empty) lines of code"

**Comment by GroophyLifefor** [comment]
YAY, IT'S PASSED 😄

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
