### PR TITLE
Upgrade to Ruby 3.2.0

### PR DESCRIPTION
**Pull request by fapdash**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Thanks for this! I currently have fairly limited time, so it'll take me a while to be able to review this.

**Comment by ErikSchierboom** [comment]
Hi! I'm happy to accept this, but two other things need to happen first (both tasks for me):

1. Fix the deploy, which is apparently broken ATM
2. Add CI that verifies the Docker image works correctly

**Comment by ErikSchierboom** [comment]
@fapdash I've looked into this, and unfortunately AWS lambda does not yet support Ruby 3+. See https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html and https://github.com/aws/aws-lambda-base-images/issues/54. As Ruby 2.7 will soon not be supported anymore, I do expect there to be changes in the future. For now, let's put this in draft and we can revisit once AWS lambda support Ruby 3.

Sorry for this!

**Comment by fapdash** [comment]
@ErikSchierboom Sad to see this blocked but nothing we can do. Thank you Erik for investigating. :)
I've subscribed to the issue and will ping here if there is progress on the AWS side.

**Comment by fapdash** [comment]
@ErikSchierboom They just released a new base image for Ruby 3.2: https://github.com/aws/aws-lambda-base-images/issues/54#issuecomment-1486974882

**Comment by ErikSchierboom** [comment]
Great news! I'll put it on my todo list (which is quite big admittedly)

**Pull request closed without merging**
