### PR TITLE
ABAP snippet extractor

### PR DESCRIPTION
**Pull request by pokrakam**
Doesn't work very well, see #41

### CODE REVIEW

**Comment by pokrakam** [comment]
Imperfect solution that skips to the first method, but shows the right info. 
May run into trouble if a method name ends with "implementation", but still better than current display.

**Comment by larshp** [comment]
thanks, looks good to me, lets try this 🚢

**Comment by pokrakam** [comment]
Hi @iHiD or @ErikSchierboom, small reminder just in case you missed the "ready for review" status change. 
Let me know if you need any changes or any other blockers.

**Comment by ErikSchierboom** [comment]
Once this is merged, I'll need to manually rerun the snippet extractor on any existing ABAP solutions. Is there perhaps a solution I could test this out on?

**Comment by ErikSchierboom** [comment]
@pokrakam There are a couple of minor ruby formatting issues: https://github.com/exercism/snippet-extractor/pull/42/checks

**Comment by pokrakam** [comment]
Thanks @ErikSchierboom , I've updated the Ruby formatting. For examples, you can use mine:
https://exercism.org/tracks/abap/exercises/scrabble-score/solutions/pokrakam
Or here's one which has end-of-line comments:
https://exercism.org/tracks/abap/exercises/run-length-encoding/solutions/pokrakam

**Comment by ErikSchierboom** [comment]
image

That seems to work! I'll update all the existing snippets.

**Pull request merged**
